# -*- coding: utf-8 -*-
"""age_calculator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dmX_0oVlOOgC7YV_2afu3EkDVoEj_V-v
"""

!pip install korean-lunar-calendar

from datetime import datetime
from korean_lunar_calendar import KoreanLunarCalendar

def calculate_age(birthdate):
    today = datetime.today()                                         # 오늘 날짜
    age = today.year - birthdate.year                                # 기본 연도 차이 계산
    if (today.month, today.day) < (birthdate.month, birthdate.day):  # 생일이 아직 안 지났으면 -1
        age -= 1
    return age

def lunar_to_solar(year, month, day, is_leap_month=False):
    cal = KoreanLunarCalendar()
    cal.setLunar(year, month, day, is_leap_month)
    solar_date = cal.getSolarDate()
    return datetime(solar_date[0], solar_date[1], solar_date[2])

def main():
    print(" 국제 표준 나이 계산기 ")
    print("1. 양력 생일 2. 음력 생일")
    choice = input("선택하세요 (1 또는 2): ")

    try:
        if choice == "1":
            birth_input = input("생년월일을 입력하세요 (YYYY-MM-DD): ")
            birthdate = datetime.strptime(birth_input, "%Y-%m-%d")
        elif choice == "2":
            lunar_input = input("음력 생일을 입력하세요 (YYYY-MM-DD): ")
            is_leap = input("윤달인가요? (예: y / 아니면 그냥 엔터): ").lower().strip() == 'y'
            year, month, day = map(int, lunar_input.split("-"))
            birthdate = lunar_to_solar(year, month, day, is_leap)
            print(f"변환된 양력 생일: {birthdate.strftime('%Y-%m-%d')}")
        else:
            print(" 잘못된 선택입니다.")
            return

        age = calculate_age(birthdate)
        print(f"당신의 만 나이는 {age}세입니다.")
    except Exception as e:
        print("오류 발생:", e)
        print("형식이 잘못되었거나 날짜를 확인해주세요.")

if __name__ == "__main__":
    main()